FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS base
WORKDIR /app
EXPOSE 8080

FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src
COPY ["Creators.csproj", "./"]
RUN dotnet restore "Creators.csproj"
COPY . .
WORKDIR "/src/"
RUN dotnet build "Creators.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "Creators.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "Creators.dll"]
