version: '3.8'

services:
  web:
    image: creators-web-app-image
    build:
      context: .
      dockerfile: DOCKERFILE
    env_file:
      - .env
    environment:
      - DB_HOST=db
      - DB_NAME=${POSTGRES_DB}
      - DB_USER=${POSTGRES_USER}
      - DB_PASSWORD=${POSTGRES_PASSWORD}
      - Redis__ConnectionString=redis:6379
    ports:
      - "80:8080"
    depends_on:
      - db
      - redis

  db:
    image: postgres:13
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:alpine

volumes:
  postgres_data: